#!/bin/bash

# Gather system information
USERNAME=$(whoami)
DATE_TIME=$(date)
HOSTNAME=$(hostname)
OS_NAME=$(source /etc/os-release && echo "$PRETTY_NAME")
UPTIME=$(uptime -p)

# Hardware Information
CPU_INFO=$(lshw -class processor | grep 'product' | awk -F ': ' '{print $2}')
RAM_SIZE=$(free -h | awk '/Mem:/ {print $2}')
DISKS=$(lsblk -d -o model,size | tail -n +2)
VIDEO_CARD=$(lshw -class display | grep 'product' | awk -F ': ' '{print $2}')

# Network Information
FQDN=$(hostname -f)
IP_ADDRESS=$(ip route get 1 | awk '{print $7; exit}')
GATEWAY=$(ip route | grep default | awk '{print $3}')
DNS_SERVER=$(grep "^nameserver" /etc/resolv.conf | awk '{print $2}')

# System Status
LOGGED_IN_USERS=$(who | awk '{print $1}' | sort | uniq | paste -sd ',')
DISK_SPACE=$(df -h --output=target,avail | tail -n +2)
PROCESS_COUNT=$(ps aux --no-heading | wc -l)
LOAD_AVERAGES=$(uptime | awk -F 'load average: ' '{print $2}')
LISTENING_PORTS=$(ss -tuln | awk 'NR>1 {print $5}' | awk -F: '{print $NF}' | sort -n | uniq | paste -sd ',')
UFW_STATUS=$(sudo ufw status | grep "Status:" | awk '{print $2}')

# Generate report
cat <<EOF

System Report generated by $USERNAME, $DATE_TIME

System Information
------------------
Hostname: $HOSTNAME
OS: $OS_NAME
Uptime: $UPTIME

Hardware Information
--------------------
CPU: $CPU_INFO
RAM: $RAM_SIZE
Disk(s):
$DISKS
Video: $VIDEO_CARD

Network Information
-------------------
FQDN: $FQDN
Host Address: $IP_ADDRESS
Gateway IP: $GATEWAY
DNS Server: $DNS_SERVER

System Status
-------------
Users Logged In: $LOGGED_IN_USERS
Disk Space:
$DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Listening Network Ports: $LISTENING_PORTS
UFW Status: $UFW_STATUS

EOF
